name: portfolio
description: My portfolio page --> jensbecker.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_strategy: ^0.2.0
  font_awesome_flutter: ^9.0.0-nullsafety
  url_launcher: ^6.0.1
  google_fonts: ^2.0.0
  fluro: ^1.7.8
  scroll_to_index: ^1.0.6
  firebase_core: ^1.0.0
  cloud_firestore: ^1.0.0
  flutter_hooks: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter