name: portfolio
description: My portfolio page --> jensbecker.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  url_strategy: ^0.1.1
  font_awesome_flutter: ^8.11.0
  url_launcher: ^5.7.10
  flutter_fadein: ^1.1.1
  simple_animations: ^2.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter