name: portfolio
description: Jens Becker portfolio page, visit jensbecker.dev

publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.1
  google_fonts: ^2.1.0
  beamer: ^0.14.0
  scroll_to_index: ^2.0.0
  firebase_core: ^1.2.1
  cloud_firestore: ^2.2.1
  flutter_hooks: ^0.17.0
  flutter_html: ^2.1.0
  flutter_svg: ^0.22.0
  easy_localization: ^3.0.0
  flutter_extensions:
    git: https://github.com/devj3ns/flutter_extensions

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0
  dart_code_metrics: ^4.0.0-dev.2


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/badges/de/
    - assets/images/badges/en/
    - assets/images/projects/icons/
    - assets/images/projects/mockups/
    - assets/images/tools_icons/
    - assets/translations/