name: portfolio
description: Jens Becker portfolio page, visit jensbecker.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  font_awesome_flutter: ^9.0.0
  url_launcher: ^6.0.1
  google_fonts: ^2.0.0
  beamer: 0.12.4
  scroll_to_index: ^2.0.0
  firebase_core: ^1.1.0
  cloud_firestore: ^1.0.7
  flutter_hooks: ^0.16.0
  flutter_html: ^2.0.0-nullsafety.1
  flutter_svg: ^0.22.0
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  pedantic: ^1.11.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/badges/de/
    - assets/images/badges/en/
    - assets/images/projects/icons/
    - assets/images/projects/mockups/
    - assets/images/tools_icons/
    - assets/translations/